export const CURRENCIES = [
    {'id': 1, 'code': 'USD', 'num': '840', 'name_tw': '美元'},
    {'id': 2, 'code': 'MYR', 'num': '458', 'name_tw': '馬來西亞令吉'},
    {'id': 3, 'code': 'CNY', 'num': '156', 'name_tw': '人民幣元'},
    {'id': 4, 'code': 'HKD', 'num': '344', 'name_tw': '港元'},
    {'id': 5, 'code': 'PHP', 'num': '608', 'name_tw': '菲律賓披索'},
    
    {'id': 6, 'code': 'SGD', 'num': '702', 'name_tw': '新加坡元'},
    {'id': 7, 'code': 'EUR', 'num': '978', 'name_tw': '歐元'},
    {'id': 8, 'code': 'GBP', 'num': '826', 'name_tw': '英鎊'},
    {'id': 9, 'code': 'IDR', 'num': '360', 'name_tw': '印尼盾'},
    {'id': 10, 'code': 'THB', 'num': '764', 'name_tw': '泰銖'},
    
    {'id': 11, 'code': 'TWD', 'num': '000', 'name_tw': '新台幣'},
    {'id': 12, 'code': 'AUD', 'num': '036', 'name_tw': '澳大利亞元'},
    {'id': 13, 'code': 'VND', 'num': '704', 'name_tw': '越南盾'},
    {'id': 14, 'code': 'JPY', 'num': '392', 'name_tw': '日圓'},
    {'id': 15, 'code': 'KRW', 'num': '410', 'name_tw': '韓圓'},
]

export const CURRENCIES_STR = {
  0: '-',
  1: 'USD',
  2: 'MYR',
  3: 'CNY',
  4: 'HKD',
  5: 'PHP',
  6: 'SGD',
  7: 'EUR',
  8: 'GBP',
  9: 'IDR',
  10: 'THB',
  11: 'TWD',
  12: 'AUD',
  13: 'VND',
  14: 'JPY',
  15: 'KRW',
  16: 'HKM',
}

export const CURRENCIES_ID = {
   USD : 1,
   MYR : 2,
   CNY : 3, 
   HKD : 4, 
   PHP : 5, 
   SGD : 6, 
   EUR : 7, 
   GBP : 8, 
   IDR : 9, 
   THB : 10, 
   TWD : 11, 
   AUD : 12, 
   VND : 13, 
   JPY : 14, 
   KRW : 15,
   HKM : 16
}

// ********** 會員身份 **********
export const ROLE_STATUS = {
    10: 'app.ROLE_STATUS.manager',
    11: 'app.ROLE_STATUS.manager_helper',
    20: 'app.ROLE_STATUS.generalAgent',
    30: 'app.ROLE_STATUS.normal_member',
    31: 'app.ROLE_STATUS.credit_member',
    40: 'app.ROLE_STATUS.banker',
    41: 'app.ROLE_STATUS.banker_withdraw_helper',
    42: 'app.ROLE_STATUS.banker_order_helper',
    43: 'app.ROLE_STATUS.banker_sell_helper',
    44: 'app.ROLE_STATUS.director',
}

export const DEPOSIT_APPROACH = {
	0: 'DEPOSIT_APPROACH.default',
	1: 'DEPOSIT_APPROACH.cash_or_check',
	2: 'DEPOSIT_APPROACH.transfer',
}

// ********** 存款狀態(主單) **********
export const DEPOSIT_MAIN_STATUS = { 
	10: 'DEPOSIT_MAIN_STATUS.UNASSIGN', //已新增儲值
	20: 'DEPOSIT_MAIN_STATUS.PROCESSING', //進行中
  25: 'DEPOSIT_MAIN_STATUS.UPLOAD_DEAL_TICKET', //已上傳單據
  30: 'DEPOSIT_MAIN_STATUS.DONE', //完成
  40: 'DEPOSIT_MAIN_STATUS.FAIL', //拒絕申請
  50: 'DEPOSIT_MAIN_STATUS.EXPIRATION', //逾時
}

// ********** 存款狀態(子單) **********
export const DEPOSIT_DETAIL_STATUS = {
	10: 'DEPOSIT_DETAIL_STATUS.UNASSIGN', //等待分配銀行帳戶
	20: 'DEPOSIT_DETAIL_STATUS.PROCESSING', //已分配銀行帳戶
  30: 'DEPOSIT_DETAIL_STATUS.VERIFICATION', //驗證中
  40: 'DEPOSIT_DETAIL_STATUS.SUCCESS', //驗證成功
  50: 'DEPOSIT_DETAIL_STATUS.CUSTOMER_SERVICE', //請聯絡客服
  60: 'DEPOSIT_DETAIL_STATUS.EXPIRATION', //逾時
}

// ********** 提款(轉帳) **********
export const WITHDRAW_STATUS_TRANSFER = { 
	20: 'WITHDRAW_STATUS.PROCESS', //莊家申請提款單
	30: 'WITHDRAW_STATUS.ACCEPT', //管理員接受申請
  40: 'WITHDRAW_STATUS.REJECT', //管理員拒絕申請
  50: 'WITHDRAW_STATUS.ADMIN_UPLOAD_TICKET', //管理員上傳單據
  60: 'WITHDRAW_STATUS.BANKER_READ', //莊家按【等待】
  70: 'WITHDRAW_STATUS.BANKER_CHECK', //已結束
}

// ********** 提款(現金) **********
// export const WITHDRAW_STATUS_CASH = { 
// 	20: 'WITHDRAW_STATUS.PROCESS', //莊家申請提款單
// 	30: 'WITHDRAW_STATUS.BANKER_CHECK', //已結束  ←----- 此處與轉帳有差別
//   40: 'WITHDRAW_STATUS.REJECT', //管理員拒絕申請
// }

export const TRANSLATE = {
  getError: 'Disconnected!',
  disconneted:'網路連線失敗',
}

// ********** 通知事件-區分大類別 **********
export const EVENT_TYPE_GROUP = {
  // 1: KYC相關(BANKER不會收到)
  2:'EVENT_TYPE_GROUP.DEPOSIT',
  3:'EVENT_TYPE_GROUP.EXCHANGE',
  4:'EVENT_TYPE_GROUP.CUSTOMER_SERVICE',
  5:'EVENT_TYPE_GROUP.ACCOUNT',
  6:'EVENT_TYPE_GROUP.WITHDRAW',
  'ALL':'EVENT_TYPE_GROUP.ALL',
}

// ********** 通知事件(鈴鐺) **********
export const EVENT_TYPE = {
  1: 'EVENT_TYPE.KYC_APPLY',  // (管理員才看得到)

  101:'EVENT_TYPE.DEPOSIT_APPLY', // (管理員才看得到)
  111:'EVENT_TYPE.DEPOSIT_UPLOAD', // (管理員才看得到)
  112:'EVENT_TYPE.DEPOSIT_EXPIRE', //儲值單過期

  // 201:'EVENT_TYPE.DEAL_APPLY', //有人對您的掛單出價
  // 2010:'EVENT_TYPE.OFFER_RECEIVE_DEAL_APPLY_PASS',
  // 211:'EVENT_TYPE.DEAL_APPLY_PASS', //掛單方已接受出價
  // 2010:'EVENT_TYPE.OFFER_RECEIVE_DEAL_APPLY_PASS',
  // 211:'EVENT_TYPE.DEAL_UPLOAD', //掛單方已轉帳，請確認是否入帳"
  // 212:'EVENT_TYPE.DEAL_UPLOAD_PASS', //出價方已確認入帳，待出價方轉帳
  // 261:'EVENT_TYPE.DEAL_DONE', //交易完成
  // 291:'EVENT_TYPE.DEAL_FAILED', //交易失敗
  // 292:'EVENT_TYPE.DEAL_REFUSE', //掛單方拒絕交易
  // 293:'EVENT_TYPE.DEAL_CANCEL', //您已取消交易

  // ********** 掛單方 **********
  201:'EVENT_TYPE.ORDER_RECEIVE_DEAL_APPLY', //有人對您的掛單出價
  2110:'EVENT_TYPE.ORDER_RECEIVE_DEAL_UPLOAD', //出價方已轉帳，請確認是否入帳
  2120:'EVENT_TYPE.ORDER_RECEIVE_DEAL_UPLOAD_PASS', //出價方已確認入帳
  2610:'EVENT_TYPE.ORDER_RECEIVE_DEAL_DONE', //交易完成
  2910:'EVENT_TYPE.ORDER_RECEIVE_DEAL_FAILED', //交易失敗
  2920:'EVENT_TYPE.ORDER_RECEIVE_DEAL_REFUSE', //您已拒絕交易
  2930:'EVENT_TYPE.ORDER_RECEIVE_DEAL_CANCEL', //出價方取消交易
  2940:'EVENT_TYPE.ORDER_RECEIVE_DEAL_AWAIT', //出價方已看過單據，請等待確認
  2950:'EVENT_TYPE.ORDER_RECEIVE_DEAL_EXPIRE', //交易逾時

  // ********** 出價方 **********
  2010:'EVENT_TYPE.OFFER_RECEIVE_DEAL_APPLY_PASS', //掛單方已接受您的出價
  211:'EVENT_TYPE.OFFER_RECEIVE_DEAL_UPLOAD', //掛單方已轉帳，請確認是否入帳
  212:'EVENT_TYPE.OFFER_RECEIVE_DEAL_UPLOAD_PASS', //(尚未定義)
  261:'EVENT_TYPE.OFFER_RECEIVE_DEAL_DONE', //交易完成
  291:'EVENT_TYPE.OFFER_RECEIVE_DEAL_FAILED', //交易失敗
  292:'EVENT_TYPE.OFFER_RECEIVE_DEAL_REFUSE', //掛單方拒絕交易
  293:'EVENT_TYPE.OFFER_RECEIVE_DEAL_CANCEL', //您已取消交易
  294:'EVENT_TYPE.OFFER_RECEIVE_DEAL_AWAIT', //掛單方看過單據，請等待確認
  295:'EVENT_TYPE.OFFER_RECEIVE_DEAL_EXPIRE', //交易逾時
  296:'EVENT_TYPE.OFFER_RECEIVE_DEAL_REFUSE_DUE_TO_AMOUNT', //此掛單已有其他排定的交易，無法滿足您的出價數量

  300:'EVENT_TYPE.CUSTOMER_SERVICE', //來自會員的新訊息
  301:'EVENT_TYPE.CUSTOMER_SERVICE_REPLY', //來自會員的回覆
  1200:'EVENT_TYPE.ADMIN_CUSTOMER_SERVICE_REPLY', //來自管理員的回覆
  1201:'EVENT_TYPE.ADMIN_CUSTOMER_SERVICE_DONE', //管理員結束一則對話

  401:'EVENT_TYPE.QUICK_DEAL_MATCHED', //您有新匹配的掛單

  901:'EVENT_TYPE.CREATE_MEMBER', //有新建立的會員
  902:'EVENT_TYPE.CREATE_AGENT', //有新建立的代理
  903:'EVENT_TYPE.CREATE_BANKER', //有新建立的莊家
  904:'EVENT_TYPE.AGENT_CREATE_MEMBER', //有代理新建會員帳號
  
  1001:'EVENT_TYPE.ADMIN_KYC_APPLY_PASS',  // (用戶才看得到)
  1091:'EVENT_TYPE.ADMIN_KYC_APPLY_FAILED', // (用戶才看得到)

  1101:'EVENT_TYPE.ADMIN_DEPOSIT_APPLY_PASS', //存款申請成功
  1102:'EVENT_TYPE.ADMIN_DEPOSIT_APPLY_FAILED', //存款申請失敗，請聯絡客服中心
  1191:'EVENT_TYPE.ADMIN_DEPOSIT_UPLOAD_PASS', //存款明細審核成功
  1192:'EVENT_TYPE.ADMIN_DEPOSIT_UPLOAD_FAILED', //存款明細審核失敗，請聯絡客服中心
  1193:'EVENT_TYPE.ADMIN_ASSIGN_DEPOSIT_BANK', //管理員分配儲值銀行帳號給存款單

  1300:'EVENT_TYPE.ADMIN_RECEIVE_WITHDRAW_ALREADY ', //存款申請成功
  1301:'EVENT_TYPE.BANKER_RECEIVE_WITHDRAW_ACCEPT', //存款申請成功
  1302:'EVENT_TYPE.BANKER_RECEIVE_WITHDRAW_REJECT', //存款申請成功
  1303:'EVENT_TYPE.BANKER_RECEIVE_WITHDRAW_ADMIN_UPLOAD', //存款申請成功
  1304:'EVENT_TYPE.ADMIN_RECEIVE_WITHDRAW_ALREADY_READ', //存款申請成功
  1305:'EVENT_TYPE.ADMIN_RECEIVE_WITHDRAW_ALREADY_CHECKED', //存款申請成功
}

export const ERRORCODE = {
  2: 'ERRORCODE.BASE_ERROR_2',
  3: 'ERRORCODE.JSON_DECODE_ERROR_3',
  4: 'ERRORCODE.SCHEMA_ERROR_4',
  5: 'ERRORCODE.DATA_MISSING_5',
  6: 'ERRORCODE.DATA_ERROR_6',
  7: 'ERRORCODE.REQUIRED_7',
  8: 'ERRORCODE.NOT_REPEAT_8',
  9: 'ERRORCODE.POSITIVE_NUMBER_9',
  10: 'ERRORCODE.FIRST_ALPHABET_10',

  11: 'ERRORCODE.GREATER_THAN_6_LESS_THAN_30_11',
  12: 'ERRORCODE.OPERATION_ERROR_12',
  13: 'ERRORCODE.IMMUTABLE_13',
  14: 'ERRORCODE.GREATER_THAN_0_LESS_THAN_5_14',
  15: 'ERRORCODE.FEEDBACK_ERROR_15',
  16: 'ERRORCODE.CURRENCY_NOT_SUPPORT_16',
  17: 'ERRORCODE.ALPHABET_NUM_ONLY_17',

  200: 'ERRORCODE.UNKNOWN_ERROR_200',
  201: 'ERRORCODE.NEED_AUTH_TOKEN_201',
  202: 'ERRORCODE.INVALID_TOKEN_202',
  203: 'ERRORCODE.TOKEN_EXPIRED_203',
  204: 'ERRORCODE.ADMIN_ONLY_204',
  205: 'ERRORCODE.PERMISSION_DENIED_205',
  206: 'ERRORCODE.PLEASE_LOGIN_206',
  207: 'ERRORCODE.ALREADY_LOGIN_207',

  301: 'ERRORCODE.USER_NOT_EXIST_301',
  302: 'ERRORCODE.USER_IS_BLOCK_302',
  303: 'ERRORCODE.USER_IS_EXIST_303',
  304: 'ERRORCODE.NEED_USERNAME_304',
  305: 'ERRORCODE.NEED_PASSWORD_305',
  306: 'ERRORCODE.PASSWORD_ERROR_306',
  307: 'ERRORCODE.EMAIL_NOT_EXIST_307',

  401: 'ERRORCODE.ID_CARD_MISSING_401',
  402: 'ERRORCODE.INVALID_VERIFY_CODE_402',
  403: 'ERRORCODE.INCORRECT_MOBILE_FORMAT_403',
  404: 'ERRORCODE.REFUSE_SEND_404',
  405: 'ERRORCODE.PHONE_VERIFIED_405',

  500: 'ERRORCODE.INTERNAL_SERVER_ERROR_500',
  501: 'ERRORCODE.BANK_ACCOUNT_NOT_EXIST_501',
  502: 'ERRORCODE.NO_DEFAULT_BANK_ACCOUNT_502',
  503: 'ERRORCODE.BANK_ACCOUNT_EXISTS_503',
  504: 'ERRORCODE.BANK_ACCOUNT_IS_IN_DEAL_504',
  505: 'ERRORCODE.NO_SUCH_BANK_FILE_505',
  506: 'ERRORCODE.FILE_IS_NOT_ALLOW_506',
  507: 'ERRORCODE.BANK_ACCOUNT_IS_FROZEN_507',
  508: 'ERRORCODE.BANK_ACCOUNT_HAS_NOT_BEEN_DISABLE_508',
  509: 'ERRORCODE.BANK_ACCOUNT_NOT_ADMIN_509',

  601: 'ERRORCODE.WALLET_NOT_FOUND_601',
  602: 'ERRORCODE.INSUFFICIENT_BALANCE_602',
  603: 'ERRORCODE.INSUFFICIENT_CREDIT_603',

  701: 'ERRORCODE.CAN_NOT_DEAL_WITH_YOURSELF_701',
  702: 'ERRORCODE.ORDER_INSUFFICIENT_BALANCE_702',
  703: 'ERRORCODE.CONTRACT_TICKET_NOT_FOUND_703',
  704: 'ERRORCODE.CANCEL_TICKET_FAIL_704',
  705: 'ERRORCODE.MARKET_NOT_EXIST_705',
  706: 'ERRORCODE.ORDER_CAN_NOT_EDIT_706',

  801: 'ERRORCODE.DEAL_CANCELED_801',
  802: 'ERRORCODE.NOT_SELLER_802',
  803: 'ERRORCODE.DEAL_NOT_FOUND_803',
  804: 'ERRORCODE.STATE_CHECK_ERROR_804',
  805: 'ERRORCODE.TICKET_CHECK_ERROR_805',
  806: 'ERRORCODE.DEAL_TIME_UP_806', //交易逾時

  901: 'ERRORCODE.EVENT_NOT_FOUND_901',

  1001: 'ERRORCODE.NO_IMAGE_1001',
  1002: 'ERRORCODE.ONLY_ONE_TIME_UPLOAD_1002',
  1003: 'ERRORCODE.NO_SELECTED_FILE_1003',
  1004: 'ERRORCODE.EXTENSION_ERROR_1004',
  1005: 'ERRORCODE.SIZE_ERROR_1005',
  1006: 'ERRORCODE.HEIGHT_ERROR_1006',
  1007: 'ERRORCODE.WIDTH_ERROR_1007',

  1101: 'ERRORCODE.DEPOSIT_STATUS_ERROR_1101',
  1102: 'ERRORCODE.DEPOSIT_EXPIRATION_1102',
  1103: 'ERRORCODE.DEPOSIT_CURRENCY_NOT_ALLOW_1103',
  1104: 'ERRORCODE.DEPOSIT_TARGET_NOT_ALLOW_1104',
  1105: 'ERRORCODE.DEPOSIT_OVER_AMOUNT_1105',
}

// ********** 流水帳(錢包紀錄) **********
export const HANDLING_FEE_TYPE = {
  0:'HANDLING_FEE_TYPE.CREATE_BANKER', //創建莊家
  1:'HANDLING_FEE_TYPE.DEAL_FEE', //手續費
  2:'HANDLING_FEE_TYPE.USER_FEE_BACK', //回饋金
  3:'HANDLING_FEE_TYPE.PLATFORM_PROFIT', //平台收益
  4:'HANDLING_FEE_TYPE.BANKER_FEE_BACK', //莊家分潤
  5:'HANDLING_FEE_TYPE.AGENT_FEE_BACK', // 代理分潤
  6:'HANDLING_FEE_TYPE.DEPOSIT_IN_CASH', //現金儲存款
  7:'HANDLING_FEE_TYPE.DEPOSIT_BY_TRANSFER', //轉帳儲值
  12:'HANDLING_FEE_TYPE.DEPOSIT_SUB_IN_CASH', //現金子單存款
  13:'HANDLING_FEE_TYPE.DEPOSIT_SUB_BY_TRANSFER' //轉帳子單存款
}

// ********** 客戶服務 **********
export const SERVICE_TYPE = {
  10:'SERVICE_TYPE.ABOUT_DEPOSIT', //訂單相關客服
  20:'SERVICE_TYPE.ABOUT_TRADE', //交易相關客服
  30:'SERVICE_TYPE.ABOUT_SUGGESTION', //網站建議相關客服
  40:'SERVICE_TYPE.ABOUT_ACCOUNT', //帳戶相關客服
  90:'SERVICE_TYPE.ABOUT_ETC', // 其他相關客服
}